- MREUnityRuntime/MREUnityRuntimeLib/Util/UtilMethods.cs
Make this method public so it can be called from the host when generating app userIds.
> Expose StringToGuid utility method

- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Constants.cs
C# side of the new version compatibility check in PR https://github.com/Microsoft/mixed-reality-extension-sdk/pull/157
> [Unity] New version compatibility scheme

- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Interfaces/ILight.cs
I inadvertently deleted the code that synced animations. Doh.
> [Unity] Quick fix for animation sync

- MREUnityRuntime/MREUnityRuntimeLib/Assets/Definitions.cs
Forgot something, merged last PR prematurely.
> Material alpha values - Fix enum values

- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
One-liner to sync rigid body again. It hasn't been getting synced for some time.
> [Unity] [Minor] Reinstate rigid body sync

- MRETestBed/Assets/TestBed Assets/Prefabs/FPSControllerWithCursor.prefab
- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/SoundStateOptions.cs
Rolloff start distance - useful for having sounds that you want to be able to fill a large space
cursor position: changed from a 3d object that wasn't properly attached to camera to a 2d object
> added rolloff start distance, and fixed testbed cursor position

- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/SoundStateOptions.cs
space. Also fixes default value for spread sound parameter.
@eanders-MS please note this may have merge conflicts with your reordering
> fixed sound updates across multiple instances of same MRE in same 

- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/ActorCommandQueue.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/NetworkCommandPayloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/PayloadTypeRegistry.cs
This ensures that actors are created before destroyed.
> Process actor destroy via command queue

- MREUnityRuntime/MREUnityRuntimeLib/Constants.cs
> We are deliberately breaking back compatibility, so updating 

- MRETestBed/Assets/Resources/Library.meta
- MRETestBed/Assets/Resources/Library/cube_20cm.prefab
- MRETestBed/Assets/Resources/Library/cube_20cm.prefab.meta
- MRETestBed/Assets/Scenes/FunctionalTest-localhost.unity
- MRETestBed/Assets/Scenes/HelloWorld.unity
- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs
* Wait until actor creation to attach children
* Add transform-test to the FT testbed scene
* Add a library cube to the testbed
* Fix the testbed HelloWorld URL
> Fix parenting to pending actors

- MRETestBed/Assets/Scenes/SynchronizationTest-localhost.unity
- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Components/BehaviorComponent.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/RigidBody.cs
- MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/RigidBodyPatch.cs
This is a fix for issue SDK:[#295](https://github.com/Microsoft/mixed-reality-extension-sdk/issues/295)
> Fix for rigid body synchronization

- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Collider.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/ColliderGeometry.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Collision/ColliderEventType.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Collision/CollisionData.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Collision/ContactPoint.cs
- MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Events/Types/ColliderEvent.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Events/Types/TriggerEvent.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/PayloadTypeRegistry.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/Payloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/ColliderPatch.cs
SDK PR#[313](https://github.com/Microsoft/mixed-reality-extension-sdk/pull/313)
> Collision and Trigger Events for Colliders

- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/Handlers/ButtonHandler.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/Behaviors/IButtonBehavior.cs
Runtime updates related to SDK#[319](https://github.com/Microsoft/mixed-reality-extension-sdk/pull/319)
> Update runtime for button API changes for grab on 3dof/2d

- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/NetworkCommandPayloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/PayloadTypeRegistry.cs
- MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/ActorPatch.cs
Runtime changes associated with SDK PR#[333](https://github.com/microsoft/mixed-reality-extension-sdk/pull/333)
> Make subscriptions only a part of the patch.

- MREUnityRuntime/MREUnityRuntimeLib/Core/Interfaces/IRigidBody.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/RigidBody.cs
- MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/RigidBodyPatch.cs
Runtime changes for SDK PR#[346](https://github.com/microsoft/mixed-reality-extension-sdk/pull/346)
> Add in IsKinematic as an exposed rigidbody property.

- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Types/MWQuaternion.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Types/MWTransform.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Types/MWVector2.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Types/MWVector3.cs
- MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Events/Types/ActorCorrectionEvent.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/NetworkCommandPayloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/Util/TransformLerper.cs
- MREUnityRuntime/MREUnityRuntimeLib/Util/Unity/MWUnityTypeExtensions.cs
Unity work for SDK PR#(350)[https://github.com/microsoft/mixed-reality-extension-sdk/pull/350]
> Grab lerping on synchronized clients

- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
This fixes an issue where the GLTF being created has its parent destroyed in that process and we get in to a state where that gltf is still created, but never initialized and is now an orphan at the root of the scene.
> Fix issue where parent is deleted during a gltf async load.

- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/SoundManager.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/NetworkCommandPayloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IVideoPlayer.cs
> mediainstance: remove startTimeOffset parameter

- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Collider.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/ColliderGeometry.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Light.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/RigidBody.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Text.cs
- MREUnityRuntime/MREUnityRuntimeLib/Factories/DefaultMaterialPatcher.cs
- MREUnityRuntime/MREUnityRuntimeLib/Util/Unity/MWUnityTypeExtensions.cs
Removed unnecessary allocations associate with type conversions between Unity types and MRE types.
> Type conversion allocation refactor

- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetCache.cs
- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Factories/DefaultMaterialPatcher.cs
- MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IAssetCache.cs
Add a mechanism to wait for an asset to exist. Fixes microsoft/mixed-reality-extension-sdk#393 and microsoft/mixed-reality-extension-sdk#394
> Add asset cache callback

- MREUnityRuntime/MREUnityRuntimeLib/Core/RigidBody.cs
Fix for issue #[401](https://github.com/microsoft/mixed-reality-extension-sdk/issues/401).
> Fix null ref exception in rigid body update

- CONTRIBUTING.md
- INTEGRATING.md
- README.md
> Replace Slack with Discord in markdown docs

- MREUnityRuntime/MREUnityRuntimeLib/App/IMixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/NetworkCommandPayloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/Payloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/RPC/RPCChannelInterface.cs
- MREUnityRuntime/MREUnityRuntimeLib/RPC/RPCInterface.cs
See https://github.com/microsoft/mixed-reality-extension-sdk/pull/449 for detailed description.
> [Unity] rpc subsystem updates

- MRETestBed/Assets/TestBed Assets/Scripts/MREComponent.cs
- MRETestBed/Assets/TestBed Assets/Scripts/UserInfo.cs
- MREUnityRuntime/MREUnityRuntimeLib/App/IMixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Interfaces/IUserInfo.cs
* Added `OnUserJoined` and `OnUserLeft` events.
* Added `InvariantId` field to `IUserInfo`. This should be set to a value that never changes (e.g. the host's userId). I need this for the web projector.
> Events for user join/leave, and a UserInfo change.

- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetCache.cs
- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IAssetCache.cs
Fixes microsoft/mixed-reality-extension-sdk#443
> Cache collider geometry in shared asset cache

- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/ActionData/BaseActionData.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/ActionData/BaseToolData.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/ActionData/PenData.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/ActionData/PenToolData.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/Actions/Action.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/BehaviorActionHandler.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/BehaviorHandlerBase.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/BehaviorHandlerFactory.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/Handlers/ButtonHandler.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/Handlers/PenHandler.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/Handlers/TargetHandler.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/Handlers/ToolHandler.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/IActionHandler.cs
- MREUnityRuntime/MREUnityRuntimeLib/Behaviors/IBehaviorHandler.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Components/ActorComponentBase.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Components/BehaviorComponent.cs
- MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/Payloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/Behaviors/IBehaviorFactory.cs
- MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/Behaviors/IPenBehavior.cs
- MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/Behaviors/IToolBehavior.cs
Unity runtime companion to SDK PR: #[484](https://github.com/microsoft/mixed-reality-extension-sdk/pull/484)
> Add in tool and pen behaviors in to runtime

- MREUnityRuntime/MREUnityRuntimeLib/Animation/Animation.cs
- MREUnityRuntime/MREUnityRuntimeLib/Animation/AnimationManager.cs
- MREUnityRuntime/MREUnityRuntimeLib/Animation/Definitions.cs
- MREUnityRuntime/MREUnityRuntimeLib/Animation/TargetPath.cs
- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/TransformPatch.cs
If a keyframe's value is a target path, poll the target for current property values, and lerp to/from those values.
> [WIP] Dynamic keyframe values

- MRETestBed/Assets/TestBed Assets/Shaders/MREDiffuseVertex.shader
Fixes https://github.com/microsoft/mixed-reality-extension-sdk/issues/562
> Fix TestBed SPI rendering

- MREUnityRuntime/MREUnityRuntimeLib/Core/Physics/IPrediction.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Physics/PredictionInterpolation.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/PhysicsBridge.cs
- MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj
> Outsource the prediction in a separate interface and class

- MREUnityRuntime/MREUnityRuntimeLib/Animation/BaseAnimation.cs
- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs
- MREUnityRuntime/MREUnityRuntimeLib/IPC/Connections/WebSocket.cs
- MREUnityRuntime/MREUnityRuntimeLib/IPC/IConnection.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/AssetCommandPayloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/NetworkCommandPayloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/Payloads.cs
- MREUnityRuntime/MREUnityRuntimeLib/Messaging/Protocols/Protocol.cs
- MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/AnimationPatch.cs
- MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/ColliderPatch.cs
- MREUnityRuntime/MREUnityRuntimeLib/RPC/RPCInterface.cs
Import json serialization improvements from @StLoch as an isolated feature.
> Move json serialization off main thread

- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetFetcher.cs
- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs
- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetManager.cs
- MREUnityRuntime/MREUnityRuntimeLib/Constants.cs
Hopefully fixes https://github.com/microsoft/mixed-reality-extension-sdk/issues/604
> Fix some problems with copy-on-writing textures

- MRETestBed/Assets/TestBed Assets/Scripts/MREComponent.cs
(Still defaults to localhost:3901)
> Read MRE URL from TestBed arguments

- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/PhysicsBridge.cs
Transfer rigid body simulation ownership when rigid body is grabbed.
Tested in both TestBed and AltspaceVR:
- when grabbed in Altspace, RBs get identity orientation
> transfer ownership on grab

- MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj
- MREUnityRuntime/MREUnityRuntimeLib/link.xml
This has also been updated on the build server to copy to output to the artifacts directory for distribution.
> Add in our link.xml file to be copied to build output directory

- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Physics/JitterBuffer.cs
https://github.com/microsoft/mixed-reality-extension-sdk/issues/610
> Enable 30Hz physics updates

- MRETestBed/Assets/Scenes/Standalone.unity
- MRETestBed/Packages/manifest.json
- MRETestBed/ProjectSettings/EditorSettings.asset
- MRETestBed/ProjectSettings/ProjectVersion.txt
- MRETestBed_MRTK/Assets/MixedRealityToolkit.Generated/CustomProfiles/MRETestBedMRTKControllerMappingProfile.asset
- MRETestBed_MRTK/Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XRSDK/Microsoft.MixedReality.Toolkit.Providers.XRSDK.WMR.asmdef
- MRETestBed_MRTK/Assets/MixedRealityToolkit.Providers/XRSDK/Microsoft.MixedReality.Toolkit.Providers.XRSDK.asmdef
- MRETestBed_MRTK/Assets/TestBed Assets/Scripts/MREComponent.cs
- MRETestBed_MRTK/Assets/XR/Settings/Oculus Settings.asset
- MRETestBed_MRTK/Assets/XR/XRGeneralSettings.asset
- MRETestBed_MRTK/ProjectSettings/EditorSettings.asset
- MRETestBed_MRTK/ProjectSettings/ProjectSettings.asset
- MRETestBed_MRTK/ProjectSettings/ProjectVersion.txt
- MRETestBed_MRTK/ProjectSettings/XRPackageSettings.asset
- MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj
- Updated the MREUnityRuntime.csproj to target the 2019.4.2f1 Unity Version DLL
- Upgraded the MRE Test Bed Unity project to target 2019.4.2f1 including upgrading to the Asset Database Version 2
- Upgraded the MRE MRTK Test Bed Unity project to target 2019.4.2f1 including upgrading to the Asset Database Version 2
> Upgrade MRE Runtime build target and test beds to Unity 2019.4.2f1

- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
Prevents weird transform offsets when switching hats.
> Keep local transform when attaching/detaching

- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
Just something I noticed after seeing intermittent exceptions from this area. Better safe than sorry.
> Fix exceptions if physics sim runs before local user joins

- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetCache.cs
- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetFetcher.cs
- MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs
- MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IAssetCache.cs
Fixes https://github.com/microsoft/mixed-reality-extension-sdk/issues/703.
> Add load locking to the asset cache API

- MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- MREUnityRuntime/MREUnityRuntimeLib/Factories/SimplePermissionsManager.cs
- MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IPermissionManager.cs
Cancel permission requests if the MRE shuts down.
> Add cancellation token to IPermissionManager

- MREUnityRuntimeLib/Assets/AssetFetcher.cs
- MREUnityRuntimeLib/Assets/AssetLoader.cs
- MREUnityRuntimeLib/Assets/Definitions.cs
Add ability to specify audio formats when type is uncertain from URI alone
> Audio Format specification
