MRETestBed/Assets/Scenes/FunctionalTest-localhost.unity, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/NetworkCommandPayloads.cs
An optimization on the Node side exposed an unsafe assumption in the client's handling of RPC messages.
Also: Sped up walk speed in the Functional Test scene.
=> [Unity] Actor patching improvements

MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Interfaces/IRigidBody.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/RigidBody.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/PatchingUtils.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/RigidBodyPatch.cs
The client was being too smart about when to process the sync-animations message. If the server sent it, trust it knows what it's doing.
Also: Removed position and rotation fields from the rigid body patch. These fields already exist in the transform.
=> Fix animation synchronization

MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
Steven noticed that reparenting wasn't working. This fixes that. FYI I coded it to preserve the child's local transform when reparenting.
=> Fix reparenting

MRETestBed/Assets/Scenes/FunctionalTest-localhost.unity, MRETestBed/Assets/TestBed Assets/Scripts/MREComponent.cs, MREUnityRuntime/MREUnityRuntimeLib/API/MREApi.cs, MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetCache.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetSource.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/Definitions.cs, MREUnityRuntime/MREUnityRuntimeLib/Factories/MWPrimitiveFactory.cs, MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/AssetCommandPayloads.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/PayloadTypeRegistry.cs, MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IAssetCache.cs, MREUnityRuntime/MREUnityRuntimeLib/Util/Unity/TextureFetcher.cs, MREUnityRuntime/MREUnityRuntimeLib/Util/UtilMethods.cs
* Add support for a new `create-asset` message, which generates a single standalone asset
* Add a public default material initialization parameter, which is used for primitives, and should be used for glTFs in Altspace.
* Added a string Uri field to Texture objects
* Added a handy `dictionary.GetOrCreate(key, defaultConstructor)` utility function
=> [Unity] Create materials and textures directly

MRETestBed/Assets/Scenes/FunctionalTest-localhost.unity, MREUnityRuntime/MREUnityRuntimeLib/API/MREApi.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/Definitions.cs, MREUnityRuntime/MREUnityRuntimeLib/Factories/DefaultMaterialApplicator.cs, MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj, MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IMaterialPatcher.cs
* Adds `AlphaMode` and `AlphaCutoff` fields to the material patch
* Abstracts Unity material reads and writes to an `IMaterialPatcher` plugin instance. This is necessary because Unity's API does not provide a shader-agnostic transparency mode accessor.
=> Support material alpha blending and cutout

MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/RigidBody.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/Converters/DashFormattedEnumConverter.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Protocols/Protocol.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/PatchingUtils.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/RigidBodyPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Util/UtilMethods.cs
Found and fixed numerous issues exposed by stressing network traffic in different ways.
- Fix patching of rigid body position and rotation (happens via transform sync, but applied to the rigid body directly).
- Rigid body patch was applying new values when none were present in the patch.  Added protection for this.
- Updated DashFormattedEnumConverter to work with Nullable enum types.
- Updated GeneratePatch functions to return null if there was no patch, enabling better actor-update deltas by not sending empty objects.
- In the case of a failure to process a network message, send a reply message indicating the failure. This will unblock any promises on the app side, and also communicate some detail about the failure.
Also:
- General cleanup of actor patching code.
=> [Unity] Fixes for stability

MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Components/AnimationComponent.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Types/MWTransform.cs
This PR fixes a bug where new clients joining an app wouldn't get the correct transforms of actors that had animated then stopped animating prior to them joining.
=> [Unity] Send an actor update when animation stops

MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/User.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/NetworkCommandPayloads.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/Payloads.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/UserPatch.cs
Removed the notion of user subscriptions and user transform. We weren't using them, and probably never will.
=> [Unity] Remove unused code

MREUnityRuntime/MREUnityRuntimeLib/Constants.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/NetworkCommandPayloads.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/Payloads.cs
Added DashFormattedEnumConverter to serializer settings so that it will be used for all enums.
=> [Unity] Use DashFormattedEnumConverter for all enums (JSON serialization)

MREUnityRuntime/MREUnityRuntimeLib/API/MREApi.cs, MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Constants.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Collider.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/ColliderGeometry.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Components/AnimationComponent.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Interfaces/ICollider.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/User.cs, MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/Converters/CollisionGeometryConverter.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/IPatchable.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Patching.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/ActorPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/ColliderPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/ColorPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/LightPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/MixedRealityExtensionObjectPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/QuaternionPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/RigidBodyPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/TextPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/TransformPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/UserPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/Vector2Patch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/Vector3Patch.cs, MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IEngineConstants.cs
Added in the backing support on Unity for setting and resetting a collider on an actor.  There is also logic adding in the collider to the initial actor patch upon creation for the case that the newly created actor already has a collider of type box, sphere or mesh.  This makes the app aware that an actor has an existing collider on an actor in the case it was there at the time of creation.
**_Note: Contains a slight cleanup effort around the IsPatched methods for our patching system._**:
=> Set collider API integration support for Unity

MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
Unity quirk: if an audiosource time is larger than the audioclip length, it doesn't automatically calculate the proper time in the middle of the loop. This works around that quirk
This also doesn't create a soundinstance if it's a non-looping sound that would have ended already - it would have played once, even though it was supposed to not play at all-
=> fix sync for looping sounds after the first playthrough has completed

MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
initial patch gets set to identity. if mre doesn't subscribe to the transform then it never gets filled out properly
=> fix actor initial transform patch

MRETestBed/ProjectSettings/ProjectSettings.asset, MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/ActorCommandQueue.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Components/AnimationComponent.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/SoundManager.cs, MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Commands/Command.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Commands/CommandManager.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Commands/ICommandManager.cs
The client can now handle messages for `Actor`s that haven't been created yet. It does this by creating a message queue for every actor and accumulating messages there. Once the actor is created, it will dispatch the messages in serial to the actor. All actor messaging goes through this mechanism now. This means that messages are processed serially per actor. This is a new constraint, but I think it will be acceptable since we have so few async actor messages, mainly create-animation.
One architectural change is that every message handler takes an onCompleteCallback parameter. Message handlers must call this exactly once and within one minute of the message being dispatched. There is new code in `CommandManager` to enforce this.
These changes are pretty extensive. Apologies for the …
=> [Unity] Move message queuing to the client

MREUnityRuntime/MREUnityRuntimeLib/Core/Components/BehaviorComponent.cs, MREUnityRuntime/MREUnityRuntimeLib/Util/Unity/AssetFetcher.cs
* Missing null check in BehaviorComponent was causing a null ref exception upon actor destroy if a call to actor.setBehavior(null) had been made previously.
* Removed a redundant template parameter from AssetFetcher.
=> Added a null check. Removed unnecessary template parameter

MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs, MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/ActorPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/AppearancePatch.cs
* Change around patching structure to include `appearance`
* Hide/show actor and children based on `appearance.enabled`
* Optimize parent actor accessor by using actor manager cache instead of calling `GetComponent`
* Fix parenting
Requres Microsoft/mixed-reality-extension-sdk#248
=> [Unity] Add visibility flag to Actor

MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs
Queuing of the actor-destroy command was causing orphaned actor queues to pile up with pending messages in them, which in turn never allowed the sync-animations payload to be processed by the authoritative peer. We really need to fix animation sync!
I will revisit the "destroying actor before it's done loading" issue later.
=> Revert my destroy actor "fix"

MRETestBed/Assets/Scenes/FunctionalTest-localhost.unity, MRETestBed/Assets/TestBed Assets/Prefabs/FunctionalTestPad.prefab, MRETestBed/Assets/TestBed Assets/Scripts/InstantiateTests.cs
Each test in the functional test scene now has a second instance of the app with the same session ID, spawned above and behind the first one so you can see them at the same time.
=> Add extra apps to functional-test scene for sync testing

MRETestBed/Assets/TestBed Assets/Scripts/Behaviors/TargetBehavior.cs, MRETestBed/Assets/TestBed Assets/Scripts/Tools/ButtonTool.cs, MRETestBed/Assets/TestBed Assets/Scripts/Tools/GrabTool.cs, MRETestBed/Assets/TestBed Assets/Scripts/Tools/TargetTool.cs, MRETestBed/Assets/TestBed Assets/Scripts/Tools/ToolUtils.cs, MREUnityRuntime/MREUnityRuntimeLib/Behaviors/BehaviorHandlerBase.cs, MREUnityRuntime/MREUnityRuntimeLib/Behaviors/Handlers/TargetHandler.cs, MREUnityRuntime/MREUnityRuntimeLib/Behaviors/IBehaviorHandler.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Components/BehaviorComponent.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/ActorPatch.cs, MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/Behaviors/ITargetBehavior.cs
This is the runtime portion of the grab functionality being added to actors. It leverages the behavior system for completing the actual interaction within the host app.  This includes an implementation of grab behavior within the MRETestBed project.
SDK reference: [PR#260](https://github.com/Microsoft/mixed-reality-extension-sdk/pull/260)
=> [UNITY-RUNTIME]: Grab functionality added to actors

MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Attachment.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Components/AnimationComponent.cs, MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IEngineConstants.cs
- Attachment component was falsely generating a patch when no changes were made.
- When an animation stops, sync the actor's final transform.
=> [Unity] Misc synchronization fixes and improvements

MREUnityRuntime/MREUnityRuntimeLib/Core/Components/AnimationComponent.cs
Fixes https://github.com/Microsoft/mixed-reality-extension-sdk/issues/254
=> Fix for #254: Actor.animateTo() causes client crash on zero duration

MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/TransformPatch.cs
Made the default constructors public for the transform patch classes.
=> Fix for transform pacth serialization issue on Android

buildMREUnityRuntimeDLL.bat
This change only refactors, no change to functionality. 
Removed IConnectionInternal that is not used.
Made several classes public: this will help integrating the part that handles the connection into another 3D engine potentially.
Replaced MixedRealityExtensionApp with its interface, where possible.
=> Refactor usage of MixedRealityExtensionApp; fix build path error with spaces

MREUnityRuntime/MREUnityRuntimeLib/API/MREApi.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/Definitions.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/MediaCommand.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/MediaStateOptions.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/SoundManager.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/VideoStreamDescription.cs, MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/NetworkCommandPayloads.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/PayloadTypeRegistry.cs, MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IVideoPlayer.cs, MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IVideoPlayerFactory.cs
Implemented a cleaner video player interface to replace the current AltspaceVR-exclusive RPC-based one.
This is now complete. 
This is a breaking change, in that old MREs would not play sounds (as payload has changed and been renamed)
=> Video Player Refactor

MRETestBed/Assets/TestBed Assets/Scripts/ResourceFactory.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetCache.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/AssetCommandPayloads.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Payloads/PayloadTypeRegistry.cs, MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IAssetCache.cs, MREUnityRuntime/MREUnityRuntimeLib/Util/Unity/AssetFetcher.cs
* Add a `ContainerId` field to `load-assets` and `create-asset` messages.
* Add an `unload-assets` message and handler
* Rewrite asset cache to look up by any associated field.
* Fix bug where testbed resource factory doesn't throw correctly.
=> Asset unloading

MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs
Fixes microsoft/mixed-reality-extension-sdk#386
* Get rid of actor update queues. There is already the network buffer and command queues in the actor manager. We don't need a third queue specifically for an actor's updates, it just makes the updates late.
* Process the actor command backlog before returning newly created actors in an `object-spawned` message. This prevents the returned patches from being out of date.
=> Fix patching during actor creation

MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs
This fixes the dreaded "timeout waiting for sync-animations" bug. When the WebSocket disconnects, we weren't clearing ActorManager's _actorCommandQueues, causing future calls to UponStable to never happen.
=> Clear actor command queues upon reset

MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs
Funny interaction detected: Upon socket disconnect, we delete all the actors and actor command queues, but were failing to clear the "upon stable" callbacks. So, if there were any queued "upon stable" callbacks, clearing the actor command queues would cause them to be invoked in the next frame. Under certain conditions, this would cause the creation of new actor command queues for now-non-existant actors, and populate them with pending commands. Since these queues would never empty, the system would never again be "stable", and therefore no "upon stable" callback would happen ever again. There's a better way to clean up: delete the app instance and recreate it. I might make that change later.
This appears to have fixed the sync-animations timeout. I'm not able to repro it anymore. It's a …
=> Clear UponStable callbacks on disconnect

MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/SoundManager.cs
queue all mediainstance commands (start/update/stop) while asset is loading.
I like the idea of creating the managing class as soon as the command comes in, so I can see if the item is being loaded or is not valid. This is the same general structure I think the asset caching could benefit from, too - then we can discard/warn if we try to use assets that haven't even been preloaded, we can execute a callback if an asset load times out.
=> queue all mediainstance commands

MREUnityRuntime/MREUnityRuntimeLib/API/MREApi.cs, MREUnityRuntime/MREUnityRuntimeLib/App/IMixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs, MREUnityRuntime/MREUnityRuntimeLib/Behaviors/BehaviorHandlerFactory.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/ActorManager.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Collider.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Protocols/Handshake.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Protocols/Protocol.cs, MREUnityRuntime/MREUnityRuntimeLib/Util/Logging/ConsoleLogger.cs, MREUnityRuntime/MREUnityRuntimeLib/Util/Logging/UnityLogger.cs
currently unity-side logging is printed to the unity log only. Ideally MRE Authors should be able to see the unity errors.  This PR adds a per-app logger class, which sends every logged message back to the MRE.
This is the Unity side of the PR. It works without SDK change.
We should also make the server say which level of logging it cares to receive - no need to waste bandwidth on diagnostics data that isn't looked at.
Caveat: This was only added to places that can access the App (maybe 65% of all places) - a number of static functions don't know which app they work for (or work for more than one app), so they will keep the old logger - most of those don't need to be brought over..
=> per-app logging

MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetCache.cs
AssetCache was throwing and exception if an asset was already cached. This breaks cases where the same MRE is running multiple instances of the same session in the same space. Specifically, this breaks running multiple instances of video-test by interrupting code execution at mixed-reality-extension-unity\MREUnityRuntime\MREUnityRuntimeLib\Assets\AssetLoader.cs(339). We never reply to the app, so it doesn't start the video.
Because we support sharing assets between multiple MRE instances in a space, I don't think this is an error condition in the first place.
Related: I think we're throwing too many exceptions where we should be instead logging errors and gracefully exiting the codepath (returning error codes back to the app, etc.). I'll log an issue for review of each exception we throw.
=> Don't throw if asset is already cached.

MREUnityRuntime/MREUnityRuntimeLib/Messaging/Protocols/Protocol.cs
Doing so will attempt to send a message over the WebSocket. If the WebSocket is disconnected, an infinite loop of errors can occur.
=> Don't log WebSocket.Send exceptions to App.Logger

MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs
Early `return` calls in PatchAppearance were skipping parts of the patch that needed to be applied.
=> Fix issue in PatchAppearance method

MREUnityRuntime/MREUnityRuntimeLib/App/IMixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
Needed by WebProjector, so it can derive the streaming url from the MRE url.
=> Expose ServerUrl on IMixedRealityExtensionApp.

MRETestBed/ProjectSettings/ProjectVersion.txt, MRETestBed/ProjectSettings/VFXManager.asset, MRETestBed/ProjectSettings/XRSettings.asset, MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj
Built and loaded the project in Unity 2019.2.12f1, and surprisingly didn't hit any problems at all. I was expecting something because of microsoft/mixed-reality-extension-sdk#332, but didn't reproduce those errors.
=> Update testbed and DLL dependency to Unity 2019.2.12f1

MREUnityRuntime/MREUnityRuntimeLib/App/IMixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/MixedRealityExtensionObject.cs
There is no guarantee that a given client has a local user, so don't assume there is one.
=> Don't assume LocalUser is defined

MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetFetcher.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoadThrottling.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs, MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj, MREUnityRuntime/MREUnityRuntimeLib/Util/Unity/AssetFetcher.cs
This is a quick fix to stabilize AltQuiz. Globally limit the number of concurrent asset fetch web requests in the MRE runtime.
=> Limit concurrent web requests

MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetFetcher.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs, MREUnityRuntime/MREUnityRuntimeLib/Messaging/Protocols/Protocol.cs
* Don't fail if asset load responses don't contain ETag headers
* Don't log connection failures back to (disconnected) server
=> Fix testing bugs

MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
- no physics bridge update when there are no rigid bodies (physics) involved.
=> If there is no rigid body update do not send physics bridge update

MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetCache.cs
The asset cache root game object can be initialized either directly in code, or from a serialized field on the MonoBehaviour that is assigned over on `Start`. If it's set it code, don't stomp it with the uninitialized serialized field. Only affects test bed, which uses the code path.
=> Don't overwrite asset cache GO with null

MRETestBed/Assets/Scenes/HelloWorld.unity, MRETestBed/Assets/Scenes/Standalone.unity, MRETestBed/Assets/Scenes/SynchronizationTest-localhost.unity, MRETestBed/Assets/Scenes/TriggerVolumeTestBed-localhost.unity, MRETestBed/Assets/TestBed Assets/Scripts/MREComponent.cs, MRETestBed_MRTK/Assets/Scenes/HelloWorld_2D.unity, MRETestBed_MRTK/Assets/Scenes/Localhost_MRTK.unity, MRETestBed_MRTK/Assets/Scenes/Standalone_2D.unity, MRETestBed_MRTK/Assets/Scenes/SynchronizationTest-localhost_2D.unity, MRETestBed_MRTK/Assets/Scenes/TriggerVolumeTestBed-localhost_2D.unity, MRETestBed_MRTK/Assets/TestBed Assets/Scripts/MREComponent.cs, MREUnityRuntime/MREUnityRuntimeLib/API/MREApi.cs, MREUnityRuntime/MREUnityRuntimeLib/App/AppManifest.cs, MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Behaviors/Contexts/TargetBehaviorContext.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Actor.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/Permissions.cs, MREUnityRuntime/MREUnityRuntimeLib/Factories/SimplePermissionsManager.cs, MREUnityRuntime/MREUnityRuntimeLib/MREUnityRuntimeLib.csproj, MREUnityRuntime/MREUnityRuntimeLib/PluginInterfaces/IPermissionManager.cs
Implement the [permission system](https://github.com/microsoft/mixed-reality-extension-sdk/pull/606) in the Unity runtime
=> [Unity] Permission system

MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs
`IAssetCache.GetVersion` returns null if no content was found, so a cached asset's version cannot be `null`, even if a server does not supply an ETag header. However, it also has to be a valid ETag. Going with the empty string here, to distinguish between both null and a real ETag.
=> Distinguish between no cached item, and unversioned cache item

MREUnityRuntime/MREUnityRuntimeLib/Core/Permissions.cs, MREUnityRuntime/MREUnityRuntimeLib/Patching/Types/UserPatch.cs
=> Report granted permissions in the user-joined message

MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetCache.cs
By moving the init to `Awake()` instead of `Start()`, MREs can be connected in `Start()` without causing problems.
=> Initialize asset cache earlier

MRETestBed/Assets/Scenes/HelloWorld.unity, MRETestBed/Assets/Scenes/Standalone.unity, MRETestBed/Assets/Scenes/SynchronizationTest-localhost.unity, MRETestBed/Assets/Scenes/TriggerVolumeTestBed-localhost.unity, MRETestBed/Assets/TestBed Assets/Scripts/MREComponent.cs, MREUnityRuntime/MREUnityRuntimeLib/API/MREApi.cs, MREUnityRuntime/MREUnityRuntimeLib/App/IMixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/User.cs, MREUnityRuntime/MREUnityRuntimeLib/Core/UserManager.cs, MREUnityRuntime/MREUnityRuntimeLib/IPC/IConnection.cs
* In #216 we accidentally removed the ability to attach things to anyone but the local user. We removed the `UserInfoProvider`, and replaced it with an `IHostAppUser` that provides the attach points. These host app users are provided to the runtime through `IMixedRealityApp.UserJoin`.
* I have added an `isLocalUser` boolean argument to that method so host app user objects for non-local users can also be passed in. This changes the convention of only local users calling UserJoin; now UserJoin should be called for all users that the client knows about.
* For non-local users on a client, we now compute both the AppId-based user ID and also the EphemeralAppId-based ID for the purposes of looking up attachments, since we don't know which one the user is going by.
=> Change assumptions to 'UserJoin' all users, not just local ones

MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
Don't null out the LocalUser reference unless it's the local user leaving.
=> Fix user input after another player leaves

MREUnityRuntime/MREUnityRuntimeLib/IPC/Connections/WebSocket.cs
Fix an issue during cleanup of the websocket where on Mac OS, the close output only on the websocket does not cause the cancellation of the awaiting read task.
=> Fix for deadlock on cleanup in Mac OS host apps

MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetFetcher.cs, MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs, MREUnityRuntime/MREUnityRuntimeLib/Constants.cs
If the asset server is not providing `ETag` headers with its responses, assume cached assets are always fresh.
=> Fix asset refcounting issues when server doesn't provide etags

MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
Don't assign default material to new actors when current is not found in cache.
=> Fix library materials

MREUnityRuntime/MREUnityRuntimeLib/Assets/AssetLoader.cs
Absent this change, some types of failures are masked by a null pointer deref
=> Fixed a null deref when last response is null

MREUnityRuntime/MREUnityRuntimeLib/App/IMixedRealityExtensionApp.cs, MREUnityRuntime/MREUnityRuntimeLib/App/MixedRealityExtensionApp.cs
Also: update the permission requests so that if an app doesn't supply a manifest, the runtime assumes it requires both tracking and interaction.
=> Add new app events OnWaitingForPermission and OnPermissionDenied
